site_name: The Rebellion of Tupac Amaru II
site_url: https://chadblack.net/Tupac/
site_author: Chad Black
site_description: A chad_black production

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode


nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Assignments: assignments.md
  - Calendar: calendar.md


plugins:
  - search

# Copyright
copyright: Copyright &copy; 2026 Chad Black

